### ISSUE TITLE
浏览记录模块有问题

### ISSUE THREAD

**Issue by wenlove** [zengxiaohui2019/Hui-Admin-Pro#16]
浏览记录部分的滑动有问题，只能直接滑到最左/最右的么，如果有很多条的浏览记录，中间部分的看不到了,如果我滑到了最右，访问浏览记录最前面的数据，也不会滑到最左边，没有继续优化么

**Comment by zengxiaohui2019** [comment]
你好，很遗憾！该项目不再维护，推荐使用vue3+vite2 研发的 [egg-admin-pro](https://gitee.com/zengxiaohui2019/egg-admin-template)
